blast:
    splits: 1000
    db_exts: [ 'nhr', 'nin', 'nsq', 'nhr', 'nin' ]
    type: nucl
    threads: 16

samap-run:
    threads: 4

data:
    - id: hu
      anndata: hu.h5ad
      transcriptome: Homo_sapiens.GRCh38.cdna.all.99.fa.gz
    - id: mu
      anndata: mu.h5ad
      transcriptome: Mus_musculus.GRCm38.cdna.all.99.fa.gz

reset_to_raw: True

cell_type_field: 'inferred_cell_type_-_ontology_labels'

outdir: 'results'
results_tag: 'E-MTAB-5061_vs_E-ENAD-15.pancreas'
